version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - User
    versioning-strategy: increase
    cooldown:
      default: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - User
    cooldown:
      default: 7
